[package]
name = "feos"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lints.rust]
unsafe_code = "deny"

[lints.clippy]
enum_glob_use = "deny"

[dependencies]
futures = "0.3.30"
netlink-packet-route = "~0.19.0"
rtnetlink = "0.14.0"
nix = { version = "0.29.0", features = ["mount", "user", "reboot", "feature", "net", "aio", "signal", "process", "fs"] }
tokio = { version = "1.38.0", features = ["full", "macros", "rt-multi-thread"] }
log = "0.4.22"
simple_logger = "5.0.0"
tonic = "0.12.1"
prost = "0.13.1"
bitflags = "2.6.0"
uuid = { version = "1.9.1", features = ["v4"] }
oci-distribution = "0.11.0"
serde = "1.0.203"
serde_json = "1.0.120"
api_client = {branch = "main",  git = "https://github.com/cloud-hypervisor/cloud-hypervisor"  }
net_util = {branch = "main",  git = "https://github.com/cloud-hypervisor/cloud-hypervisor"  }
vmm = { branch = "main",  git = "https://github.com/cloud-hypervisor/cloud-hypervisor", features = ["kvm"] }
openssl = { version = "0.10.66", features = ["vendored"] }
libcgroups = { branch = "main", git = "https://github.com/containers/youki",  default-features = false, features = ["v2",] }
libcontainer = { branch = "main", git = "https://github.com/containers/youki", default-features = false, features = [ "v2",] }
dhcproto = "0.12.0"
rand = "0.8.5"
pnet = "0.35.0"
thiserror = "1.0.63"
anyhow = "1.0.86"
tar = "0.4"
flate2 = "1.0"
tokio-stream = "0.1.15"
chrono = "0.4"
futures-util = "0.3"
futures-core = "0.3"
async-stream = "0.3"
libc = "0.2"

[build-dependencies]
tonic-build = "0.12.1"

[workspace]
members = [
    "client",
]
